apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    argocd.argoproj.io/instance: nginx
  name: nd
spec:
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: nginx
status:
  loadBalancer: {}
